import type { IncomingHttpHeaders } from "http";
import type { Config } from "@/node/config";
import type { AIService } from "@/node/services/aiService";
import type { ProjectService } from "@/node/services/projectService";
import type { WorkspaceHarnessService } from "@/node/services/workspaceHarnessService";
import type { GateRunnerService } from "@/node/services/gateRunnerService";
import type { GitCheckpointService } from "@/node/services/gitCheckpointService";
import type { LoopRunnerService } from "@/node/services/loopRunnerService";
import type { WorkspaceService } from "@/node/services/workspaceService";
import type { MuxGatewayOauthService } from "@/node/services/muxGatewayOauthService";
import type { ProviderService } from "@/node/services/providerService";
import type { TerminalService } from "@/node/services/terminalService";
import type { EditorService } from "@/node/services/editorService";
import type { WindowService } from "@/node/services/windowService";
import type { UpdateService } from "@/node/services/updateService";
import type { TokenizerService } from "@/node/services/tokenizerService";
import type { ServerService } from "@/node/services/serverService";
import type { MenuEventService } from "@/node/services/menuEventService";
import type { VoiceService } from "@/node/services/voiceService";
import type { MCPConfigService } from "@/node/services/mcpConfigService";
import type { ExperimentsService } from "@/node/services/experimentsService";
import type { WorkspaceMcpOverridesService } from "@/node/services/workspaceMcpOverridesService";
import type { MCPServerManager } from "@/node/services/mcpServerManager";
import type { TelemetryService } from "@/node/services/telemetryService";
import type { SigningService } from "@/node/services/signingService";
import type { FeatureFlagService } from "@/node/services/featureFlagService";
import type { SessionTimingService } from "@/node/services/sessionTimingService";
import type { SessionUsageService } from "@/node/services/sessionUsageService";
import type { TaskService } from "@/node/services/taskService";
import type { CoderService } from "@/node/services/coderService";

export interface ORPCContext {
  config: Config;
  aiService: AIService;
  projectService: ProjectService;
  workspaceHarnessService: WorkspaceHarnessService;
  gateRunnerService: GateRunnerService;
  gitCheckpointService: GitCheckpointService;
  loopRunnerService: LoopRunnerService;
  workspaceService: WorkspaceService;
  taskService: TaskService;
  providerService: ProviderService;
  muxGatewayOauthService: MuxGatewayOauthService;
  terminalService: TerminalService;
  editorService: EditorService;
  windowService: WindowService;
  updateService: UpdateService;
  tokenizerService: TokenizerService;
  serverService: ServerService;
  menuEventService: MenuEventService;
  voiceService: VoiceService;
  mcpConfigService: MCPConfigService;
  workspaceMcpOverridesService: WorkspaceMcpOverridesService;
  mcpServerManager: MCPServerManager;
  featureFlagService: FeatureFlagService;
  sessionTimingService: SessionTimingService;
  telemetryService: TelemetryService;
  experimentsService: ExperimentsService;
  sessionUsageService: SessionUsageService;
  signingService: SigningService;
  coderService: CoderService;
  headers?: IncomingHttpHeaders;
}
